Feature/add recognitions
lblod/app-verenigingen-loket pull request #3
Opened 2023-12-18 09:24 UTC by Andresdev02

2023-12-18 09:36 UTC, oscartison approved these changes

2023-12-18 10:37 UTC, bdevloed requested changes
looks good, just one detail about the new-resource-base

2023-12-18 10:37 UTC, bdevloed commented on config/resources/domain.json
> +      "new-resource-base": "https://data.vlaanderen.be/ns/"
Best to use `http://data.lblod.info/id/` as a base. i.e.:
`http://data.lblod.info/id/erkenningen/`

2023-12-19 07:50 UTC, bdevloed approved these changes

2023-12-19 07:51 UTC, merged